# Generated by Django 3.2.6 on 2022-07-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('mel_class', models.CharField(max_length=255)),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
